### ISSUE TITLE
Roles needed for speech recognition and translation

### ISSUE THREAD

**Issue by Ryuno-Ki** [c3subtitles/live-subtitles-test-backend#11]
I imagine a similar construct like currently for admin:

 1. Introduce new roles for:
  - Speech-Input
  - Speech-correct
 1. Only Admins can grant this roles to users.
 1. Create new room locks for speech processing.
 1. Only users with those roles (+admin) can enter a room, locked for only those.

**Comment by percidae** [comment]
In my opinion that worked on the congress due to changes from marudor?!
