### ISSUE TITLE
Make shortcuts clickable (or change design)

### ISSUE THREAD

**Issue by Ryuno-Ki** [c3subtitles/live-subtitles-test-backend#4]
@percidae invited me today to test this app.

I found it confusing for the shortcuts on the right hand pane to be not clickable (as they looked so).

 1. So either make them insert the expanded term on the cursor's position on click.
 1. Or change their view to not indicate that they're clickable (which they aren't).

**Comment by percidae** [comment]
I would close that, because during writing live subtitles there is no time to click sth anyway.
